analyzer:
  # 启用更宽松的分析模式
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  
  # 忽略特定类型的警告
  errors:
    # 语法相关
    missing_required_param: ignore       # 缺少必需参数
    missing_return: ignore              # 缺少返回值
    unused_element: ignore              # 未使用的元素
    unused_local_variable: ignore       # 未使用的局部变量
    dead_code: ignore                   # 死代码
    avoid_init_to_null: ignore          # 避免初始化为null
    unnecessary_null_comparison: ignore  # 不必要的null检查
    
    # Flutter特定
    prefer_const_constructors: ignore   # 推荐const构造函数
    prefer_const_declarations: ignore   # 推荐const声明
    avoid_print: ignore                # 避免使用print
    prefer_final_fields: ignore         # 推荐final字段
    
    # 样式相关
    camel_case_types: ignore            # 驼峰命名类型
    non_constant_identifier_names: ignore # 非常量标识符名称
    library_prefixes: ignore            # 库前缀
    directives_ordering: ignore         # 指令顺序

  # 排除生成的文件
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/generated/**'
    - '**/build/**'

# 宽松的linter规则
linter:
  rules:
    # 只启用最基本的规则
    - always_declare_return_types
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_renaming_method_parameters
    - curly_braces_in_flow_control_structures
    - empty_catches
    - library_names
    - no_duplicate_case_values
    - null_closures
    - prefer_is_empty
    - prefer_is_not_empty
    - type_init_formals
    - unnecessary_nullable_for_final_variable_declarations
    - use_build_context_synchronously
    - use_rethrow_when_possible