name: Flutter Build

on:
  push:
    branches:
      - master
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.png'
      - '**/*.jpg'

jobs:
  build:
    name: Build
    if: ${{! contains(github.event.head_commit.message, '[skip ci]')}}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Test connection
        run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"

      - name: Fix flutter SDK folder permission
        run: git config --global --add safe.directory /tmp/flutter/--

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - name: Display Flutter version
        run: flutter --version

      - name: Create ignoreConfig.dart
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: lib/common/config/ignoreConfig.dart
          FILE_DATA: class NetConfig { static const CLIENT_ID = "${{ secrets.CLIENT_ID }}"; static const CLIENT_SECRET = "${{ secrets.CLIENT_SECRET }}";}
      
      - name: Install dependencies
        run: flutter pub get

      - name: generate keystore
        run: echo $ENCODED_KEYSTORE | base64 -di > android/app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}

      - name: Build apk
        run: flutter build apk --build-name=1.0.${{ github.run_number }} --build-number=${{ github.run_number }} --release  --no-shrink
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}

      - name: Generate tag
        id: generated_tag
        run: echo "tag=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
      
      - name: Use the tag
        run: echo "Generated tag:" + ${{ steps.generated_tag.outputs.tag }}
  
      - name: Release
        if: contains(github.event.commits[0].message, '[release]')
        id: upload_release_asset
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          files: build/app/outputs/apk/release/app-*.apk
          tag_name: "Pre-Release-${{ steps.generated_tag.outputs.tag }}"
          body: "Github Action Build Pre-Release"
          name: "${{github.event.commits[0].message}}"

  tag-release:
    name: tag-release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          
      - name: Test connection
        run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"

      - name: Fix flutter SDK folder permission
        run: git config --global --add safe.directory /tmp/flutter/--
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - name: generate ignoreConfig.dart
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: lib/common/config/ignoreConfig.dart
          FILE_DATA: class NetConfig { static const CLIENT_ID = "${{ secrets.CLIENT_ID }}"; static const CLIENT_SECRET = "${{ secrets.CLIENT_SECRET }}";}
      
      - name: Install dependencies
        run: flutter pub get

      - name: Create keystore
        run: echo $ENCODED_KEYSTORE | base64 -di > android/app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}

      - name: Build apk
        run: flutter build apk --build-name=1.0.${{ github.run_number }} --build-number=${{ github.run_number }} --release  --no-shrink
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}

      - name: Release
        id: upload_release_asset
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: build/app/outputs/apk/release/app-*.apk
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          make_latest: true